export const metaKeywords = [
  'Link shortener',
  'Link shortening',
  'URL shortener',
  'URL shortening',
  'Shorten links',
  'Link management',
  'Custom short URLs',
  'Branded links',
  'Secure link shortening',
  'Free URL shortener',
  'Short link analytics',
  'URL redirection service',
  'Shorten URLs for social media',
  'Link tracking',
  'Tiny URL',
  'Shorten links for Instagram',
  'URL cloaking',
  'QR code generator',
  'Reduce link length',
  'Easy link sharing',
  'Short domain service',
  'Affiliate link shortener',
  'Bulk link shortening',
  'Link shortener API',
  'Privacy-focused URL shortener',
  'Short links for email marketing',
  'Customizable short links',
  'Link compression',
];
